/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.*;
import javax.swing.JOptionPane;

/**
 *
 * @author user2
 */
public class VentanaNArreglo extends javax.swing.JFrame {
    Cliente cliente = null;
    Auto auto = null;
    double km;
    /**
     * Creates new form VentanaNArreglo
     */
    public VentanaNArreglo(Cliente clienteR, Auto autoR) {
        this.setIconImage(Clientes.getIconImage("imagenes/llave_plus.png"));
        this.setLocationRelativeTo(null);
        cliente = clienteR;
        auto = autoR;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfKm = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar arreglo");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Km ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 17, -1, -1));
        getContentPane().add(tfKm, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 12, 339, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (tfKm.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Complete el campo solicitado");
        }else{
            try {
                km = Double.parseDouble(tfKm.getText());
                Arreglo arreglo = new Arreglo(km);
                Entrada entrada = new Entrada("inicio del arreglo", 0);
                arreglo.addEntrada(entrada);
                auto.addArreglos(arreglo);
                Mail mail = new Mail(cliente.getMail(), "Proceso de reparacion iniciado \nse avisara cuando este terminado");
                JOptionPane.showMessageDialog(this, "Guardado");
                tfKm.setText("");
            }catch(RuntimeException e){
                JOptionPane.showMessageDialog(this, "inserte un km valido");
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        VentanaArreglos ven = new VentanaArreglos(cliente, auto);
        ven.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tfKm;
    // End of variables declaration//GEN-END:variables

}
