/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
import clases.*;
import javax.swing.JOptionPane;
/**
 *
 * @author user2
 */
public class VentanaNEntrada extends javax.swing.JFrame {
    Cliente cliente = null;
    Auto auto = null;
    Arreglo arreglo = null;
    /**
     * Creates new form VentanaNEntrada
     */
    public VentanaNEntrada(Cliente clienteR, Auto autoR, Arreglo arregloR) {
        this.setIconImage(Clientes.getIconImage("imagenes/carpeta_plus.png"));
        this.setLocationRelativeTo(null);
        cliente = clienteR; 
        auto = autoR;
        arreglo = arregloR;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfCoste = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        btnGuardar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nueva entrada");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Coste");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 17, -1, -1));

        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Informacion");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 45, -1, -1));
        getContentPane().add(tfCoste, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 12, 253, -1));

        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 68, 376, 102));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        VentanaEntradas ven = new VentanaEntradas(cliente, auto, arreglo);
        ven.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(arreglo.getEstado().equals("Incompleto")){
            if (tfCoste.getText().equals("") || jTextPane1.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Complete los campos solicitados");
            }else{
                try {
                    double a = Double.parseDouble(tfCoste.getText());
                    Entrada entrada = new Entrada(jTextPane1.getText(), a);
                    arreglo.addEntrada(entrada);
                    JOptionPane.showMessageDialog(this, "Entrada guardada");
                    tfCoste.setText("");
                    jTextPane1.setText("");
                }catch(RuntimeException e){
                    JOptionPane.showMessageDialog(this, "Error: Inserte nuevamente el coste");
                    tfCoste.setText("");
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "Este arreglo no se puede modificar porque ya esta finalizado");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField tfCoste;
    // End of variables declaration//GEN-END:variables
}
