/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Juani
 */
public class VentanaClientes extends javax.swing.JFrame {

    /**
     * Creates new form VentenaClientes
     */
    public VentanaClientes() {
        this.setLocationRelativeTo(null);
        initComponents();
        this.setIconImage(Clientes.getIconImage("imagenes/cliente.png"));
        load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lClientes = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAddCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        btnVerAutos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lnBuscar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clientes");
        setAutoRequestFocus(false);
        setBounds(new java.awt.Rectangle(579, 200, 0, 0));
        setFocusCycleRoot(false);
        setFocusable(false);
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lClientes.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        jScrollPane1.setViewportView(lClientes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 68, 547, -1));

        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 45, -1, -1));

        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Telefono");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 45, -1, -1));

        btnAddCliente.setText("Agregar Cliente");
        btnAddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, -1, -1));

        btnEliminarCliente.setText("Eliminar Cliente");
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        btnVerAutos.setText("Ver Auto(s)");
        btnVerAutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerAutosActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerAutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Buscar :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 17, -1, -1));

        lnBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lnBuscarKeyReleased(evt);
            }
        });
        getContentPane().add(lnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 12, 480, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddClienteActionPerformed
        VentanaNCliente ven = new VentanaNCliente();
        ven.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddClienteActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
        try {
            int confirmacion = JOptionPane.showConfirmDialog(this, "Desea eliminar al cliente: "+Clientes.getClientes().get(lClientes.getSelectedIndex()).getNombre()+"?");
            if(JOptionPane.OK_OPTION == confirmacion){
                Clientes.removeCliente(Clientes.getClientes().get(lClientes.getSelectedIndex()));
                load();
            }
            }catch(RuntimeException e){
                JOptionPane.showMessageDialog(this, "Selecione un cliente");
            }
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    private void btnVerAutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerAutosActionPerformed
        try { 
            VentanaAutos ven = new VentanaAutos(Clientes.getClientes().get(lClientes.getSelectedIndex()));
            ven.setVisible(true);
        }catch(RuntimeException e){
            JOptionPane.showMessageDialog(this, "Selecione un cliente");            
        }
    }//GEN-LAST:event_btnVerAutosActionPerformed

    private void lnBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnBuscarKeyReleased
        DefaultListModel model = new DefaultListModel();
        for (Cliente cliente : Clientes.search(lnBuscar.getText())) {
                model.addElement(cliente);
        }
        lClientes.setModel(model);
    }//GEN-LAST:event_lnBuscarKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCliente;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton btnVerAutos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lClientes;
    private javax.swing.JTextField lnBuscar;
    // End of variables declaration//GEN-END:variables
    private void load() {
        DefaultListModel model = new DefaultListModel();
        for (Cliente cliente : Clientes.getClientes()) {
            model.addElement(cliente);        
        }
        lClientes.setModel(model);
    }

}
