/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
import clases.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Juani
 */
public class VentanaAutos extends javax.swing.JFrame {
    Cliente cliente = null;
    /**
     * Creates new form VentanaAutos
     */
    public VentanaAutos(Cliente clienteR) {
        cliente = clienteR;
        this.setLocationRelativeTo(null);
        this.setIconImage(Clientes.getIconImage("imagenes/auto.png"));
        initComponents();
        lblCliente.setText(cliente.getNombre());
        load();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lAutos = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnAddAuto = new javax.swing.JButton();
        btnVerArreglos = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Autos");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(254, 238, 238));
        jLabel1.setText("Cliente :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        lblCliente.setForeground(new java.awt.Color(254, 254, 254));
        getContentPane().add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 12, 374, 14));

        lAutos.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        jScrollPane1.setViewportView(lAutos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 63, 437, -1));

        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Marca");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 34, -1, -1));

        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Modelo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 34, -1, -1));

        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Patente");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 34, -1, -1));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 71, -1));

        btnAddAuto.setText("Agregar auto");
        btnAddAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAutoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 127, -1));

        btnVerArreglos.setText("Ver arreglo(s)");
        btnVerArreglos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerArreglosActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerArreglos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        btnEliminar.setText("Eliminar auto");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAutoActionPerformed
        VentanaNAuto ven = new VentanaNAuto(cliente);
        ven.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddAutoActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnVerArreglosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerArreglosActionPerformed
        try {
            VentanaArreglos ven = new VentanaArreglos(cliente, cliente.getAutos().get(lAutos.getSelectedIndex()));
            ven.setVisible(true);
            this.dispose();
        }catch(RuntimeException e){
            JOptionPane.showMessageDialog(this, "Seleccione un auto");
        }
    }//GEN-LAST:event_btnVerArreglosActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            int confirmacion = JOptionPane.showConfirmDialog(this, "Desea eliminar el auto : "+cliente.getAutos().get(lAutos.getSelectedIndex()).getModelo()+"?");
            if (JOptionPane.OK_OPTION == confirmacion){
                cliente.removeAuto(cliente.getAutos().get(lAutos.getSelectedIndex()));
                load();
            }
        }catch(RuntimeException e){
            JOptionPane.showMessageDialog(this, "Seleccione un auto");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAuto;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnVerArreglos;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lAutos;
    private javax.swing.JLabel lblCliente;
    // End of variables declaration//GEN-END:variables
  private void load() {
        DefaultListModel model = new DefaultListModel();
        for (Auto auto : cliente.getAutos()) {
            model.addElement(auto);        
        }
        lAutos.setModel(model);
    }
}
