/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
import clases.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *  
 * @author Juani
 */
public class VentanaTArreglo extends javax.swing.JFrame {
    Cliente cliente = null;
    Auto auto = null;
    Arreglo arreglo = null;
    /**
     * Creates new form VentanaTArreglo
     */
    public VentanaTArreglo(Cliente clienteR, Auto autoR, Arreglo arregloR) {
        this.setIconImage(Clientes.getIconImage("imagenes/ok.png"));
        this.setLocationRelativeTo(null);
        cliente = clienteR;
        auto = autoR;
        arreglo = arregloR;        
        initComponents();
        load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblKm = new javax.swing.JLabel();
        btnTerminar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lEntradas = new javax.swing.JList<>();
        lblCosteT = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Terminar arreglo");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Fecha de inicio");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Km de inicio");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 35, -1, -1));

        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Coste total");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 58, -1, -1));

        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Entradas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 87, -1, -1));

        lblFecha.setForeground(new java.awt.Color(254, 254, 254));
        getContentPane().add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 12, 287, 17));

        lblKm.setForeground(new java.awt.Color(254, 254, 254));
        getContentPane().add(lblKm, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 35, 292, 17));

        btnTerminar.setText("Terminar");
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnTerminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, -1));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        lEntradas.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        jScrollPane2.setViewportView(lEntradas);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 110, 406, 107));

        lblCosteT.setForeground(new java.awt.Color(254, 254, 254));
        getContentPane().add(lblCosteT, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 58, 292, 17));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed
        if (arreglo.getEstado().equals("Incompleto")){
            arreglo.changeEstado();
            Mail mail = new Mail(cliente.getMail(), "El arreglo esta terminado \nsu coste es de $ "+arreglo.getCostet());
            JOptionPane.showMessageDialog(this, "Arreglo terminado guardado");
        }else{
            JOptionPane.showMessageDialog(this, "Este arreglo ya esta finalizado");
        }
    }//GEN-LAST:event_btnTerminarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        VentanaEntradas ven = new VentanaEntradas(cliente, auto, arreglo);
        ven.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTerminar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lEntradas;
    private javax.swing.JLabel lblCosteT;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblKm;
    // End of variables declaration//GEN-END:variables

    private void load(){
        lblFecha.setText(arreglo.getFecha());
        lblKm.setText(arreglo.getKm()+" km");
        lblCosteT.setText("$ "+arreglo.getCostet());
        DefaultListModel model = new DefaultListModel();
        for (Entrada entrada : arreglo.getEntradas()) {
            model.addElement(entrada);        
        }
        lEntradas.setModel(model);
    }
}
