/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
import clases.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
        
/**
 *
 * @author user2
 */
public class VentanaArreglos extends javax.swing.JFrame {
    Cliente cliente = null;
    Auto auto = null ;
    
    /**
     * Creates new form VentanaArreglos
     */
    public VentanaArreglos(Cliente clienteR, Auto autoR) {
        this.setLocationRelativeTo(null);
        this.setIconImage(Clientes.getIconImage("imagenes/llave.png"));
        cliente = clienteR;
        auto = autoR;
        initComponents();
        load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lArreglos = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        lblAuto = new javax.swing.JLabel();
        btnAddAreglo = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnRemoveArreglo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnVerEntradas = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Arreglos");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lArreglos.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        jScrollPane1.setViewportView(lArreglos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 58, 376, 120));

        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Auto :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        lblAuto.setForeground(new java.awt.Color(254, 254, 254));
        getContentPane().add(lblAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 12, 330, 17));

        btnAddAreglo.setText("Agregar Arreglo");
        btnAddAreglo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAregloActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddAreglo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, 30));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 70, -1));

        btnRemoveArreglo.setText("Remover arreglo");
        btnRemoveArreglo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveArregloActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemoveArreglo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Estado");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 35, -1, -1));

        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Fecha");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 35, -1, -1));

        btnVerEntradas.setText("Ver entradas");
        btnVerEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEntradasActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerEntradas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Coste");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 35, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        VentanaAutos ven = new VentanaAutos(cliente);
        ven.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnAddAregloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAregloActionPerformed
        VentanaNArreglo ven = new VentanaNArreglo(cliente, auto);
        ven.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddAregloActionPerformed

    private void btnVerEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEntradasActionPerformed
        try {
            VentanaEntradas ven = new VentanaEntradas(cliente, auto, auto.getArreglos().get(lArreglos.getSelectedIndex()));
            ven.setVisible(true);
            this.dispose();
        }catch(RuntimeException e){
            JOptionPane.showMessageDialog(this, "Seleccione una falla");
        }
    }//GEN-LAST:event_btnVerEntradasActionPerformed

    private void btnRemoveArregloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveArregloActionPerformed
        try {
            int confirmacion = JOptionPane.showConfirmDialog(this, "Desea eliminar el arreglo seleccionado ?");
            if (JOptionPane.OK_OPTION == confirmacion){
                auto.removeArreglo(auto.getArreglos().get(lArreglos.getSelectedIndex()));
                load();
            }
        }catch(RuntimeException e){
            JOptionPane.showMessageDialog(this, "Seleccione un arreglo");
        }
    }//GEN-LAST:event_btnRemoveArregloActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAreglo;
    private javax.swing.JButton btnRemoveArreglo;
    private javax.swing.JButton btnVerEntradas;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lArreglos;
    private javax.swing.JLabel lblAuto;
    // End of variables declaration//GEN-END:variables
    private void load(){
        DefaultListModel model = new DefaultListModel();
        lblAuto.setText(auto.getMarca()+" ( "+auto.getModelo()+" )");     
        for (Arreglo arreglo : auto.getArreglos()) {
            model.addElement(arreglo);        
        }
        lArreglos.setModel(model);
    }
}
